### ISSUE TITLE
tutorial values don't match the pulse() values

### ISSUE THREAD

**Issue by x011** [julienfouilhe/automate-gate-opening#1]
Hi,
The tutorial values on `Step 1: Sniff the signal` don't match the `pulse()` values. Where should I get the low and high values? from the `rtl_433` output or the triq website? I'm confused about this.
My output is:

[https://triq.org/pdv/#AAB021030601C0037C24608091809090918180909091809181818181818090918091809255](https://triq.org/pdv/#AAB021030601C0037C24608091809090918180909091809181818181818090918091809255)

**Comment by julienfouilhe** [comment]
@x011 Sorry for the delay, I hadn't enabled notifications on this repository. I personally copied the values in the triq link. But your code seems very complicated, mine was very easy in comparison.
