### ISSUE TITLE
RTL-SDR alternative ?

### ISSUE THREAD

**Issue by janbaum** [julienfouilhe/automate-gate-opening#2]
Hasn't anyone found a cheaper alternative instead of the expensive RTL-SDR mensioned ?

**Comment by julienfouilhe** [comment]
Sorry for the delay, I guess you could try a cheap 433Mhz receiver, but I wasn't able to figure out how to replay the received signal, it should technically be possible though, but my knowledge is limited and I had better luck with the RTL-SDR unfortunately.

Please tell me if you found a solution, I'm interested!
